name: Atualiza Palpites IA
on:
  schedule:
    - cron: '3 15 * * *' # 19:00 Maputo - 1x por dia
  workflow_dispatch: # Botão pra rodar manual

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests pytz
      - run: python update.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Atualiza jogos IA" || exit 0
          git push
