name: Atualiza Palpites IA
on:
  schedule:
    - cron: '40 06 * * *' # 20:40 Maputo
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install requests pytz
      - run: python update.py
      - run: |
          git config user.name "bot"
          git config user.email "
